version: '3'
services:
  backend:
    container_name: backend_api_container
    image: node:12.14.1
    volumes:
      - ./:/app
    working_dir: /app/backend
    user: "node"
    depends_on:
      - mongo   
    ports:
      - 8001:8001
    command: nodemon ./bin/www
  mongo:
    container_name: mongo_db_container
    image: mongo:4.2.2
    expose:
      - 27017
    ports:
      - 27022:27017    
    volumes:
      - ~/data/db:/data/db

  frontend:
    container_name: frontend_container
    image: node:12.14.1
    user: "node"
    working_dir: /home/node/frontend
    environment:
      - PORT=3000
    volumes:
      - ./frontend/:/home/node/frontend
    ports:
      - '8000:3000'
    networks:
      - default